[package]
name = "harper-py"
version = "0.1.0"
edition = "2021"

[lib]
name = "harper_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20", features = ["extension-module"] }
harper-core = { git = "https://github.com/fundamental-ai/harper.git", tag = "v0.1.0" }
harper-comments = { git = "https://github.com/fundamental-ai/harper.git", tag = "v0.1.0" }
serde_json = "1.0"

# Add workspace table to make it standalone
[workspace]